import Image from 'next/image';
import { bookingAssets, bookingYear } from '../booking';
import { SampleSongListCard } from '../components/SampleSongListCard';
import { ShrinkingHeader } from '../components/ShrinkingHeader';
import { createPageMetadata, siteConfig } from '../seo';
import { soundGear } from '../sound-gear';

export const metadata = createPageMetadata({ title: 'Press Kit & Venue Assets', description: 'Download Rock Steady logos, press photos, sample song list, stage plot, input list, and venue one-sheet.', path: '/press', image: siteConfig.horizontalLogoPreviewPath, imageAlt: 'Rock Steady band logo' });
const pressPhotos = ['/images/show-08.jpg','/images/show-10.jpg','/images/show-04.jpg'];

export default function PressPage() { return <><ShrinkingHeader /><main className="min-h-screen bg-[#050505] pb-20 pt-36 text-white"><section className="px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase text-[#37d67a]">For venues &amp; media</p><h1 className="mt-3 max-w-4xl text-5xl font-black leading-tight sm:text-6xl">Press kit, production info, and booking assets.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/72">Everything needed to promote and advance a Rock Steady show, all in one place.</p>
  <div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="flex flex-col border border-white/12 bg-[#101010] p-6"><p className="text-sm font-black uppercase text-(--rock-steady-yellow)">Logos</p><div className="relative mt-4 h-28"><Image src={siteConfig.horizontalLogoPreviewPath} alt="Rock Steady logo" fill sizes="(min-width: 1280px) 25vw, (min-width: 768px) 50vw, 100vw" className="object-contain" /></div><div className="mt-auto flex gap-2 pt-5"><a href={siteConfig.horizontalLogoPath} download className="border border-white/15 px-3 py-2 text-xs font-black uppercase">Horizontal PNG</a><a href={siteConfig.logoPath} download className="border border-white/15 px-3 py-2 text-xs font-black uppercase">Stacked PNG</a></div></div>
  <div className="border border-white/12 bg-[#101010] p-6"><p className="text-sm font-black uppercase text-(--rock-steady-yellow)">Press photos</p><div className="mt-4 grid grid-cols-3 gap-2">{pressPhotos.map((src,index) => <a key={src} href={src} download className="relative aspect-square overflow-hidden border border-white/12"><Image src={src} alt={`Downloadable Rock Steady press photo ${index + 1}`} fill sizes="(min-width: 1280px) 8vw, (min-width: 768px) 16vw, 30vw" className="object-cover" /></a>)}</div></div>
  <SampleSongListCard imagePath={siteConfig.sampleSongListPath} previewImagePath={siteConfig.sampleSongListPreviewPath} variant="pressKit" />
  <div className="border border-white/12 bg-[#101010] p-6"><p className="text-sm font-black uppercase text-(--rock-steady-yellow)">Venue documents</p><div className="mt-4 grid gap-2">{bookingAssets.map(asset => <a key={asset.href} href={asset.href} download className="border border-white/15 bg-black/30 px-4 py-3 text-sm font-black uppercase hover:text-(--rock-steady-yellow)">{asset.title} PDF</a>)}</div><p className="mt-5 text-xs font-bold text-white/55">Updated for {bookingYear} venue advance.</p></div></div>
  <div className="mt-6 border border-white/12 bg-white/[0.045] p-6"><p className="text-sm font-black uppercase text-(--rock-steady-yellow)">Short bio</p><p className="mt-3 max-w-5xl leading-7 text-white/78">Rock Steady is a female-fronted Phoenix cover band built for packed, loud, crowd-first nights. The set spans classic rock, &apos;80s and &apos;90s sing-alongs, and dance-floor staples - Joan Jett, Heart, Tom Petty, ZZ Top, AC/DC and more - played with vocals up front and guitar hooks that cut through.</p></div></div></section>
  <section id="production" className="mt-20 bg-[#101010] px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase text-[#37d67a]">Production</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Pro sound, dialed in for the room.</h2><div className="mt-10 grid gap-4 sm:grid-cols-3">{soundGear.map(gear => <a key={gear.name} href={gear.url} target="_blank" rel="noreferrer" className="flex flex-col items-center gap-5 border border-white/12 bg-black/30 p-8"><Image src={gear.src} alt={gear.name} width={gear.width} height={gear.height} unoptimized className="h-9 w-auto" /><p className="text-sm font-black uppercase text-white/64">{gear.role}</p></a>)}</div></div></section></main></>; }
